import { Map } from "./map.js";
import { Player } from "./player.js";
import { Settings } from "./settings.js";
import { Obstacle } from "./obstacle.js";
const settings = new Settings(100, 50);
const map = new Map(settings);
const player = new Player(settings, map);
settings.init(map, player);
map.init(settings, player);
new Obstacle(200, 200, map).init();
new Obstacle(600, 200, map).init();
new Obstacle(420, 451, map).init();
console.log(test);
